### ISSUE TITLE
video formatting

### ISSUE THREAD

**Issue by woanderer** [wilson1yan/VideoGPT#21]
Wondering if you have also encountered the 

assert len(video) == self.num_frames
error in torchvision/datasets/vid_utils.py .

I tried converting from avi to mp4 but it did not help, Thanks again.

**Comment by wilson1yan** [comment]
Unfortunately, I haven't seen this issue before. Maybe the video is too short and there aren't enough frames?

Or, to debug, you could try reading in the video yourself as a numpy array, and then save it using something like `scikit-video` or `cv2`, since I know `mp4` files saved from those should definitely have no issues be read using `VideoClips`

**Comment by woanderer** [comment]
thanks, tried that, still nothing. Ended up changing 

/torchvision/datasets/video_utils.py

'''python
        assert len(video) == self.num_frames, "{} x {}".format(
            video.shape, self.num_frames
        )
'''
to:

'''python
        if len(video) != self.num_frames:
            video = video[:self.num_frames]
'''

**Comment by woanderer** [comment]
thanks, tried that, still nothing. Ended up changing

/torchvision/datasets/video_utils.py

```python
assert len(video) == self.num_frames, "{} x {}".format(
video.shape, self.num_frames
)
```
to:

```python
if len(video) != self.num_frames:
video = video[:self.num_frames]
```
